server:
  port: 9000

logging:
  level:
    root: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: laiacano
    r2dbc:
      repositories:
        enabled: false
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: vaginitisvagina@gmail.com
    password: lbjvmrecujahxsnr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false