spring:
  cloud:
    gcp:
      sql:
        database-name: laiacano
        instance-connection-name: indigo-skyline-386510:europe-southwest1:laiacano
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    username: postgres
    password: yu_32IEt?9gvvsB0
    name: laiacano
