spring:
  cloud:
    gcp:
      sql:
        database-name: laiacano
        instance-connection-name: indigo-skyline-386510:europe-southwest1:laiacano
  r2dbc:
    username: postgres
    password: =;&O4]T'=#*rHEq~
