server:
  port: 9000

spring:
  cloud:
    gcp:
      sql:
        enabled: false
  datasource:
    url: jdbc:h2:mem:laiacano
    driverClassName: org.h2.Driver
    username: sa
    password: admin
    database-platform: org.hibernate.dialect.H2Dialect