spring:
  cloud:
    gcp:
      sql:
        instance-connection-name: indigo-skyline-386510:europe-southwest1:laiacano
        database-name: laiacano
  datasource:
    username: postgres
    password: =;&O4]T'=#*rHEq~