server:
  port: 9000

logging:
  level:
    root: DEBUG

spring:
  cloud:
    gcp:
      sql:
        enabled: false
  datasource:
    url: jdbc:h2:mem:laiacano
    driverClassName: org.h2.Driver
    username: sa
    password: admin
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: vaginitisvagina@gmail.com
    password: lbjvmrecujahxsnr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false